package com.adriano.digitalizador;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.pdf.PdfDocument;import android.net.Uri;import android.view.*;import android.widget.*;import com.google.mlkit.vision.documentscanner.*;import java.io.*;import java.text.*;import java.util.*;
public class MainActivity extends Activity{
 static final int SAVE=3,SCAN=4; ArrayList<File> pages=new ArrayList<>(); ImageView preview; TextView count; RadioGroup filters;
 public void onCreate(Bundle b){super.onCreate(b);buildUi();restore();refresh();}
 TextView txt(String s,int sp){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(Color.rgb(22,32,42));v.setPadding(4,8,4,8);return v;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}
 public void buildUi(){ScrollView sv=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(28,24,28,28);root.setBackgroundColor(Color.rgb(245,247,250));TextView title=txt("Digitalizador PDF",28);title.setTextColor(Color.rgb(23,63,95));title.setTypeface(null,1);root.addView(title);root.addView(txt("Aponte para a folha: o app detecta as bordas, corrige a perspectiva e remove o fundo automaticamente.",15));preview=new ImageView(this);preview.setScaleType(ImageView.ScaleType.CENTER_INSIDE);preview.setBackgroundColor(Color.rgb(232,238,244));root.addView(preview,new LinearLayout.LayoutParams(-1,620));count=txt("",16);root.addView(count);LinearLayout row=new LinearLayout(this);Button scan=btn("Digitalizar");Button gal=btn("Importar / Digitalizar");row.addView(scan,new LinearLayout.LayoutParams(0,-2,1));row.addView(gal,new LinearLayout.LayoutParams(0,-2,1));root.addView(row);TextView ok=txt("✓ Recorte automático  •  ✓ Correção de perspectiva  •  ✓ Fundo removido",13);ok.setTextColor(Color.rgb(35,110,72));root.addView(ok);filters=new RadioGroup(this);filters.setOrientation(RadioGroup.HORIZONTAL);String[] fs={"Cor","Cinza","P/B"};for(int i=0;i<3;i++){RadioButton r=new RadioButton(this);r.setText(fs[i]);r.setId(100+i);filters.addView(r);}filters.check(100);root.addView(filters);LinearLayout edit=new LinearLayout(this);Button rot=btn("Girar última");Button rem=btn("Remover última");edit.addView(rot,new LinearLayout.LayoutParams(0,-2,1));edit.addView(rem,new LinearLayout.LayoutParams(0,-2,1));root.addView(edit);Button exp=btn("Salvar PDF");root.addView(exp);Button clear=btn("Limpar documento");root.addView(clear);root.addView(txt("O processamento do documento acontece no aparelho.",12));sv.addView(root);setContentView(sv);scan.setOnClickListener(v->scanner());gal.setOnClickListener(v->scanner());rot.setOnClickListener(v->rotate());rem.setOnClickListener(v->remove());clear.setOnClickListener(v->clearAll());exp.setOnClickListener(v->savePicker());}
 File dir(){File d=new File(getFilesDir(),"scans");d.mkdirs();return d;}String stamp(){return new SimpleDateFormat("yyyyMMdd_HHmmss_SSS",Locale.US).format(new Date());}
 void restore(){File[] a=dir().listFiles((d,n)->n.startsWith("page_")&&n.endsWith(".jpg"));if(a!=null){Arrays.sort(a,Comparator.comparing(File::getName));pages.addAll(Arrays.asList(a));}}
 void scanner(){GmsDocumentScannerOptions o=new GmsDocumentScannerOptions.Builder().setGalleryImportAllowed(true).setPageLimit(50).setResultFormats(GmsDocumentScannerOptions.RESULT_FORMAT_JPEG).setScannerMode(GmsDocumentScannerOptions.SCANNER_MODE_FULL).build();GmsDocumentScanner s=GmsDocumentScanning.getClient(o);s.getStartScanIntent(this).addOnSuccessListener(x->{try{startIntentSenderForResult(x,SCAN,null,0,0,0);}catch(IntentSender.SendIntentException e){toast("Não foi possível abrir o scanner.");}}).addOnFailureListener(e->toast("Scanner indisponível: "+e.getMessage()));}
 protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(c!=RESULT_OK)return;if(r==SCAN&&data!=null){GmsDocumentScanningResult z=GmsDocumentScanningResult.fromActivityResultIntent(data);if(z!=null&&z.getPages()!=null){int n=0;for(GmsDocumentScanningResult.Page p:z.getPages()){File f=importPage(p.getImageUri());if(f!=null){pages.add(f);n++;}}if(n>0)toast(n==1?"Documento detectado e recortado automaticamente.":n+" páginas detectadas e recortadas automaticamente.");}refresh();}else if(r==SAVE&&data!=null)makePdf(data.getData());}
 File importPage(Uri u){try(InputStream in=getContentResolver().openInputStream(u)){return write(BitmapFactory.decodeStream(in));}catch(Exception e){toast("Falha ao importar a página digitalizada.");return null;}}
 File write(Bitmap b){if(b==null)return null;try{int max=Math.max(b.getWidth(),b.getHeight());if(max>2400){float s=2400f/max;Bitmap n=Bitmap.createScaledBitmap(b,Math.round(b.getWidth()*s),Math.round(b.getHeight()*s),true);b.recycle();b=n;}File f=new File(dir(),"page_"+stamp()+".jpg");try(FileOutputStream o=new FileOutputStream(f)){b.compress(Bitmap.CompressFormat.JPEG,94,o);}b.recycle();return f;}catch(Exception e){return null;}}
 void refresh(){if(pages.isEmpty()){preview.setImageDrawable(null);count.setText("Nenhuma página adicionada");}else{count.setText(pages.size()+(pages.size()==1?" página recortada":" páginas recortadas"));preview.setImageBitmap(BitmapFactory.decodeFile(pages.get(pages.size()-1).getPath()));}}
 void rotate(){if(pages.isEmpty())return;File f=pages.get(pages.size()-1);Bitmap b=BitmapFactory.decodeFile(f.getPath());Matrix m=new Matrix();m.postRotate(90);Bitmap n=Bitmap.createBitmap(b,0,0,b.getWidth(),b.getHeight(),m,true);try(FileOutputStream o=new FileOutputStream(f,false)){n.compress(Bitmap.CompressFormat.JPEG,94,o);}catch(Exception e){}b.recycle();n.recycle();refresh();}
 void remove(){if(pages.isEmpty())return;pages.remove(pages.size()-1).delete();refresh();}void clearAll(){for(File f:pages)f.delete();pages.clear();refresh();}
 void savePicker(){if(pages.isEmpty()){toast("Adicione pelo menos uma página.");return;}Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/pdf");i.putExtra(Intent.EXTRA_TITLE,"Documento_"+new SimpleDateFormat("yyyy-MM-dd_HH-mm",Locale.getDefault()).format(new Date())+".pdf");startActivityForResult(i,SAVE);}
 Bitmap filter(Bitmap s){int id=filters.getCheckedRadioButtonId();if(id==100)return s;Bitmap o=Bitmap.createBitmap(s.getWidth(),s.getHeight(),Bitmap.Config.ARGB_8888);int[] p=new int[s.getWidth()*s.getHeight()];s.getPixels(p,0,s.getWidth(),0,0,s.getWidth(),s.getHeight());for(int i=0;i<p.length;i++){int c=p[i],g=Math.round(Color.red(c)*.299f+Color.green(c)*.587f+Color.blue(c)*.114f);if(id==102)g=g>155?255:0;p[i]=Color.rgb(g,g,g);}o.setPixels(p,0,s.getWidth(),0,0,s.getWidth(),s.getHeight());return o;}
 void makePdf(Uri u){PdfDocument d=new PdfDocument();try{int n=1;for(File f:pages){Bitmap a=BitmapFactory.decodeFile(f.getPath()),b=filter(a);PdfDocument.Page p=d.startPage(new PdfDocument.PageInfo.Builder(1240,1754,n++).create());Canvas c=p.getCanvas();c.drawColor(Color.WHITE);float sc=Math.min(1140f/b.getWidth(),1654f/b.getHeight()),w=b.getWidth()*sc,h=b.getHeight()*sc;c.drawBitmap(b,null,new RectF((1240-w)/2,(1754-h)/2,(1240+w)/2,(1754+h)/2),new Paint(Paint.FILTER_BITMAP_FLAG));d.finishPage(p);if(b!=a)b.recycle();a.recycle();}try(OutputStream o=getContentResolver().openOutputStream(u)){d.writeTo(o);}toast("PDF salvo com sucesso.");}catch(Exception e){toast("Erro ao gerar PDF.");}finally{d.close();}}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
}
